### ISSUE TITLE
n8n Integration 

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#100]
Create n8n integration like ToolJet do.

https://docs.tooljet.com/docs/data-sources/n8n/

n8n is the best open source automation platform currently.

**Comment by lmx1117** [comment]
thanks for your proposal, we have already put it on our roadmap: [https://github.com/orgs/openblocks-dev/projects/1](https://github.com/orgs/openblocks-dev/projects/1)

**Comment by jimhuds** [comment]
> Create n8n integration like ToolJet do.
> 
> https://docs.tooljet.com/docs/data-sources/n8n/
> 
> n8n is the best open source automation platform currently.

Isn't this done easiest by a simple REST get, with the Webhook link? What extra functionality are you thinking of

**Comment by MichalisDBA** [comment]
@jimhuds It's just simpler and easier to integrate with the n8n webhook system. Tooljet has it.

**Comment by jimhuds** [comment]
> @jimhuds It's just simpler and easier to integrate with the n8n webhook system. Tooljet has it.
Looking at the Toojet docs, it just looks like a way to do a REST call but named n8n instead. You still have to type your Webhook link in, doesn't look like there is any account integration?

What do you see as the benefit of doing it like that rather than just through the existing REST connection, is it so that it's easier to see which queries are n8n?

**Comment by Simonaaaa-C** [comment]
Hi, we now support n8n datasource! 
Please check and update to the latest version [v1.1.5](https://github.com/openblocks-dev/openblocks/releases/tag/v1.1.5). Thanks for your suggestion and patience!

**Comment by MichalisDBA** [comment]
Great thank you. It works!
