### ISSUE TITLE
Native JMESPath for querying JSON results

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#104]
Consider adding support for native JMESPath.

For example i have a JSON result that queried through a Woocommerce store.

I want to get from the meta_data object all the values from a specific meta_key.

Copy paste the JSON from here

https://pastebin.com/09TsK8JF

to here and parse it

https://jsonparser.org/

Then click the filter icon and add

[*].meta_data[?key=='mikti_timi_emag'][value]

![image](https://user-images.githubusercontent.com/68512501/206388691-7ba06762-778e-4e3c-81b5-72c4da15a8d8.png)

With this simple one liner i got all the nested values from the meta_data object that have a specific key without looping and writing custom javascript code etc.

**Comment by lmx1117** [comment]
I'm soooo sorry, I misrepresented, I double-checked that we will not support native JMESPath in the future either🙇🥲

**Comment by MichalisDBA** [comment]
@lmx1117 Is there a specific reason for that? or it's simply not in the roadmap?

**Comment by lmx1117** [comment]
Because OB is universal, and there are so many js libraries, so it’s not possible that when users mention one, we are to support one. For users who don't need it, it will add extra overhead. And when users put this library into the workspace settings, it will take effect for all the applications in the workspace, and actually the final effect is similar to what OB support.

**Comment by MichalisDBA** [comment]
Ok thank you.
