### ISSUE TITLE
Server-Side Searching / Filtering for Table Comproment

### ISSUE THREAD

**Issue by MichalisDBA** [openblocks-dev/openblocks#123]
Implement server-side search / filtering functionality to the Table comproment just like appsmith or tooljet.

https://docs.appsmith.com/reference/widgets/table#setup-server-side-search

https://docs.tooljet.com/docs/widgets/table/

When you fetch many rows from a sql query, for example 70-100k the whole app becomes unresponsive. Maybe there is a way to handle this amount of data in future releases.

**Comment by neon-balcony** [comment]
Hi @MichalisDBA ,

Thanks for the post! I totally agree with you that for a larger set of data we should do filtering and pagination in server side and actually this is already supported in Openblocks now. 

For the demo below, first we can use `where` clause and `limit offset` clause in PostgreSQL combining with parameters from `input1` and `table1`:
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/118174126/207531283-262ec375-6a70-4f16-8656-601d64efb19e.png">


Second, we need to specify **total row count** field of the table since we're only providing a page size of data to the table.
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/118174126/207531625-5a71d853-5a71-481c-a419-d788fe969d17.png">

**Comment by MichalisDBA** [comment]
@neon-balcony Thanks, i'll give it a try with MySQL and see how it goes. Thanks for the explanation.

**Comment by MichalisDBA** [comment]
@neon-balcony Yes, i did that and everything is working now.

The drawback although is that you cannot now filter the results because it tries to filter the data of the current page offset and maybe you have the filtered data on another offset. I don't know if there is a workaround.

**Comment by neon-balcony** [comment]
> @neon-balcony Yes, i did that and everything is working now.
> 
> The drawback although is that you cannot now filter the results because it tries to filter the data of the current page offset and maybe you have the filtered data on another offset. I don't know if there is a workaround.

Hi @MichalisDBA, I may not get your point on the _drawback_ thing, could you elaborate more on that or give us a real example?

**Comment by MichalisDBA** [comment]
@neon-balcony 

Yes. So we implemented the server side filtering and we get 10 rows of results per page. Let's say all the results are 20. So we have 2 pages of 10 rows each.

If you want to Search or Filter the data of the table after that, you are filtering and searching based on these 10 rows currently showing at the table. Maybe the result you want is at row 15 which is at the next table page but it would not show up after the filtering.

**Comment by MichalisDBA** [comment]
![Animation](https://user-images.githubusercontent.com/68512501/207565740-8fb7262c-e03f-408d-8509-ecbc902d8ad7.gif)

**Comment by neon-balcony** [comment]
Hi @MichalisDBA,

Thanks for the GIF, that was very clear! 
I think the root cause for this is there're two filters controlling the table's data, one is the **CUS** input box which controlls the pagination on the server side. The other is the table filter that filters data locally in the browser. So if you wish to use server-side pagination, narrow all your filters in one place. I would suggest using using multiple input boxes and wire them with your query for server-side data filtering.

**Comment by MichalisDBA** [comment]
@neon-balcony Thank you, i will try to do that.
