### ISSUE TITLE
Question: how encode URL parameters

### ISSUE THREAD

**Issue by swright-eti** [openblocks-dev/openblocks#126]
I have a URL that will look something like this:

`device-api/v1/models?deviceTypeName=encodeURIComponent("{{devices_table.selectedRow.deviceType}}")`

An error gets returned by encodeURIComponent is evaluated as a string, not a function. 

`Invalid request URL: https://beta1.dev.eti.software/device-api/v1/models?deviceTypeName=encodeURIComponent(Huawei ONT).`

How do I get around this?

**Comment by neon-balcony** [comment]
Hi @swright-eti ,

For cases where you write plain URL along with JS code, you need to enclose all JS code inside `{{ }}`. So one way to solve your case you can be adapting your code to this way:
```
device-api/v1/models?deviceTypeName={{encodeURIComponent(devices_table.selectedRow.deviceType)}}
```

But I would highly recommend you using **Parameters** field which is simpler and clearer since `encodeURIComponent` is automatically done for you:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/118174126/207756816-0bbe6afd-6612-4b13-9c84-9f76d2827161.png">

**Comment by swright-eti** [comment]
LOL using parameters would have been way smarter. Thanks for correcting me on that.
