### ISSUE TITLE
Add ability to trust a self-signed certificate

### ISSUE THREAD

**Issue by m4rcelpl** [openblocks-dev/openblocks#156]
Hi, 
Now if I want to use internal API with self-signed certificate, i can't. 
My suggestion is a checkbox like in postman.
<img width="769" alt="Zrzut ekranu 2022-12-29 o 09 07 20" src="https://user-images.githubusercontent.com/13198386/209922367-147085bf-148d-4779-aa49-2ffa8b4ce194.png">

**Comment by Simonaaaa-C** [comment]
Hi, this feature is supported now. Please check and update to the latest version v1.1.4. Thanks for your advice and patience.
![image](https://user-images.githubusercontent.com/102499458/213111088-4dd0b772-b78f-441e-a776-325bdea40207.png)

**Comment by virtzilla** [comment]
I only see this option available if I look at the REST API option under the global Data Sources. I really want to see the option under an individual query in my app when selecting the "REST Query" option within it. Is there a means to make it appear there, or do I have to use a global?

I was thinking I had an old version and after verifying I had the latest, thought something was amiss with my deployment  after seeing your screen shot and not seeing it in there.

**Comment by neon-balcony** [comment]
Hey @virtzilla, first we use the idea of [data source](https://docs.openblocks.dev/data-sources/data-source-basics) to store credentials and common settings for a bunch of queries. For example you can create a REST API data source with common URL prefix (e.g. `https://my_api.com/api/`) and shared headers (e.g. `X-REQUEST-TOKEN token-cpsitnvj34`) so that all queries that originated from it don't need to declare those on their own. 

Second, as per the `REST API Query` you mentioned to create REST queries, you can think it as a system predefined REST API data source with **empty** settings inside, and it can relieve users from creating empty dummy REST API data sources.

At last for the `SSL Cert Verfication` setting, we would consider it as a data source level feature and you can only configure that in a newly created data source rather than the predefined one. The good news is that all subsequent queries which need this configuration can benefit from this data source.

**Comment by virtzilla** [comment]
In my use case, I have dynamic endpoints that I want to define on the fly for the API endpoints (appliances) - thus trying to avoid "predefined" data sources. I have a form value for the hostname, thus the path I was taking.

> At last for the SSL Cert Verfication setting, we would consider it as a data source level feature and you can only configure that in a newly created data source rather than the predefined one

Stepping back, I think such a setting equally applies in both areas and shouldn't be limited to the data source level. I know at least for me on my quest, I wasted a fair amount of time trying to find the newly referenced option where it wasn't (and that led me down a path of why I wasn't seeing it) where I would expect to.

**Comment by neon-balcony** [comment]
Got it, in this case I think you can still create an REST API data source with empty host/path and `SSL Cert Verfication` configured.
