### ISSUE TITLE
Oracle Support?

### ISSUE THREAD

**Issue by architectdrone** [openblocks-dev/openblocks#17]
Hello,

Are there any plans to support the Oracle Database System?

**Comment by hanshuai** [comment]
Oracle integration is currently available in cloud version, and we are working on providing it in community version.  Stay tuned!

**Comment by MichalisDBA** [comment]
Yes Oracle support would be great. I don't know which version and beyond you would support but it would be great if you let us use older dependencies to connect to older Oracle versions

**Comment by architectdrone** [comment]
Awesome... looking forward to it!

**Comment by architectdrone** [comment]
I was wondering why it was on the cloud version but not the local version? I was looking into the difficulty of adding it myself but I wasn't sure if it would be better to wait, or what sort of difficulty was being run into. 

also, @MichalisDBA, I was wondering, when you said 

> but it would be great if you let us use older dependencies to connect to older Oracle versions

What did you mean?

**Comment by MichalisDBA** [comment]
@architectdrone I don't know what connectors they use to connect to databases. For example i use another project that gets data from oracle databases using JDBC. Newest JDBCs does not work with older Oracle versions. So i swapped the JDBC of the project i use with an older JDBC and then worked.

**Comment by architectdrone** [comment]
Oh, that's definitely weird. I don't really know much about that, to be honest.

**Comment by joktexan** [comment]
@hanshuai, First, allow me to thank you and all those contributing to this project. It has a super-polished feel to the interface and the functionality is mind-blowingly cool.  Not sure, but I suspect this is because your team doesn't release code unless it is very close to 'production-ready'.  

Your statement regarding dependency debt rings true.  Would it be possible to create a branch or tag with the current state of the Oracle plugin?  I would love to help out in any way, if I can

**Comment by neon-balcony** [comment]
Hi, oracle support is introduced in latest version, check it out.

@joktexan thanks for the suggestion! It's true we want it our code to be 'polished' and production-ready so that you won't be let down by some mysterious or rookie code mistake,  but now we're considering creating feature branches here and let our community check its progress and participate.

**Comment by architectdrone** [comment]
Awesome!!!
