### ISSUE TITLE
Query Input being wrapped with single quotes when empty

### ISSUE THREAD

**Issue by zuroma999** [openblocks-dev/openblocks#231]
Not sure if this is the intended result of Openblocks.

I have a query properly set up with a single input as follows:

`SELECT ...
LEFT JOIN Meetings m ON m.id=c.from_meeting
  {{more_where}}
  ORDER BY c._modified DESC`

The intention is to use the `more_where` input to dynamically insert a WHERE clause as needed, as in the following code:

```
//show all clips or a single row
const $where = ( 'single_id' in url.query ) ? 'WHERE c.id=' + url.query.single_id : '';
all_clips.run({
  more_where: $where
});

```
but whenever that code runs I get a query error. Seems like openblocks is wrapping all inputs with single quotes? Not sure if this is the intention?

<img width="1157" alt="Screenshot 2023-02-01 at 2 08 39 PM" src="https://user-images.githubusercontent.com/49953523/216174754-5d0ceb2e-4ca8-4c9c-a0e7-37cd2a8a5045.png">

**Comment by zuroma999** [comment]
Otherwise, it would be great if query objects had methods to fetch/set the query string, so that queries could be dynamically changed before running.

**Comment by neon-balcony** [comment]
Hey @zuroma999 thanks for the post, Openblocks enforces prepared statement by default for `{{ }}` expression thus treat it like a binding value rather than a literal string. So if you wish to concatenate SQL string dynamically, please 

1. Open your data source settings, toggle `Enable toggling prepared statements for queries` on
<img width="588" alt="image" src="https://user-images.githubusercontent.com/118174126/216231357-864c4b1d-d661-4b18-9662-c31fad3da15b.png">

2. Find the query and go to **Advanced** tab, toggle `Disable prepared statement` on
<img width="600" alt="image" src="https://user-images.githubusercontent.com/118174126/216231526-a522efff-6238-4f52-9ef3-b254157a1516.png">

3. Execute your queries again, you should find it working now:
<img width="705" alt="image" src="https://user-images.githubusercontent.com/118174126/216231720-18be2f23-af92-496a-9abf-efbedc8e4887.png">
<img width="890" alt="image" src="https://user-images.githubusercontent.com/118174126/216231680-55d5e22c-7133-42ae-a4ea-626df0327f88.png">

**Comment by zuroma999** [comment]
That’s great. Thanks so much!
