### ISSUE TITLE
Unable to handle Int64 (NumberLong) from MongoDB

### ISSUE THREAD

**Issue by RuneStone0** [openblocks-dev/openblocks#292]
If you store a number such as `1631764775259480064` in MongoDB it becomes a NumberLong object. When Openblocks query mongo the number returned will become a float and the last part of the number is zeroed out to `1631764775259480000`. See screenshot for evidence.
On the left: Openblocks
On the right: MongoDB Compass
![ob-bug](https://user-images.githubusercontent.com/6630442/222996313-9f042ed2-b8ad-46d5-8bab-2cae81e3c6aa.png)

**Comment by neon-balcony** [comment]
Hey @RuneStone0, thanks for the post! It seems that when this data gets rendered in our browser, JS cannot handle it properly. I would suggest doing a simple `$toString` mapping to your original request so that you can get the whole data in string format: 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/118174126/223641267-6fedf163-effc-48e7-a115-dc8937428edc.png">

```JSON
{
    "$addFields": {
      "valueInStr": {
        "$toString": "$value"
      }
    }
 }
```
