### ISSUE TITLE
Dynamic parameters for query

### ISSUE THREAD

**Issue by meowcat** [openblocks-dev/openblocks#35]
Is there a way to append a dynamically generated parameter string to a REST query?
Use case:
* REST endpoint http://myendpoint/api/tabledata/
* A javascript transformer named `mytable_filter` collects the `filters` from a table and composes a parameter list:
```
return mytable.filter.filters.map(f => `filter{${f.columnKey}.${f.operator}}=${f.filterValue}`).join('&')
```
* My query has parameters `sort[]` => `{{mytable.sortColumn}}`, `page` => `{{mytable.pageNo}}`.
* Now I want to "tack on" `&{{mytable_filter}}` at the end of the query, such that the final URL is
`http://myendpoint/api/tabledata/?sort[]={{mytable.sortColumn}}&page={{mytable.pageNo}}&{{mytable_filter.value}}`
For example: 
`http://myendpoint/api/tabledata/?sort[]=name&page=3&filter{mass.gt}=200`

What I tried:
* setting URL to `http://myendpoint/api/tabledata/?{{mytable_filter.value}}`, `http://myendpoint/api/tabledata/?{{mytable_filter.value}}&` and some variations of this -> "Invalid request URL"
* adding a parameter with no `key` and value `{{mytable_filter.value}}` => query works but filter is not active (I guess the parameter is silently discarded)
* adding a parameter with no `value` and key `{{mytable_filter.value}}` => run failed: {"code":"HTTPBAD_REQUEST","message":""}
* Some variations like putting "&" as key

**Comment by neon-balcony** [comment]
Interesting question, I tried parsing with your format with java.net.URI:
```Java
URI uri = new java.net.URI("https://test/?filter{mass.gt}=200"); 
```
and it failed with msg
```Java
java.net.URISyntaxException: Illegal character in query at index 20: https://test/?filter{mass.gt}=200
	at java.base/java.net.URI$Parser.fail(URI.java:2974)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3233)
	at java.base/java.net.URI$Parser.parse(URI.java:3175)
	at java.base/java.net.URI.<init>(URI.java:623)
```
Apparently this error is caused by the brackets since it's not a valid character in url, so the I think solution for your issue can be like this:
1. Adapt your filter transformer with calling `encodeURIComponent` on brackets part (which is the key in your case):
```JavaScript
return table2.filter.filters
  .map((f) => {
    var key = `filter{${f.columnKey}.${f.operator}}`
    var encodedKey = encodeURIComponent(key)
    return encodedKey + `=${f.filterValue}`
  })
  .join("&");
```
2. Tack on your filter after your url and it should work well then:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/118174126/202467768-28c04ad0-0dc9-4738-bb76-3013d75bdfcc.png">

**Comment by meowcat** [comment]
awesome, thanks!
