### ISSUE TITLE
Echarts source

### ISSUE THREAD

**Issue by leoborlot** [openblocks-dev/openblocks#37]
Hi guys, your app is amazing, i´ve tryed to gen a new EChart model, but I cannot give a success.

Witch lib did you use for this echarts?
Is https://echarts.apache.org/?

**Comment by ggbond2077** [comment]
yes, it is. 
what problems did you encountered?

**Comment by leoborlot** [comment]
Ive try to copy a example code from site to replicate in openblock but the code have some sintaxes interpreted as error in OB

**Comment by ggbond2077** [comment]
> Ive try to copy a example code from site to replicate in openblock but the code have some sintaxes interpreted as error in OB

Could you show me your example code?  the option field only support JSON value.  you'd better surround code by {{ }}.

**Comment by leoborlot** [comment]
Look this record, maybe I dont understand the process...

![chrome_cB7okaVlWD](https://user-images.githubusercontent.com/20361821/202712668-5b4b57e9-0164-4bd6-bc5d-ed79f8ac3412.gif)

**Comment by neon-balcony** [comment]
Hi @leonardoborlot,

Check out this record below, actually in Openblocks we should copy and paste in the **Option** config in JSON format, rather than the whole JS code. 

Sorry about the inconvience, we'll add more explanations and examples about that.
![echart-json-demo](https://user-images.githubusercontent.com/118174126/202738569-ff7bc4d6-244e-43e6-a9dc-bcda19d2c0e9.gif)

**Comment by leoborlot** [comment]
Good, did it work!
