### ISSUE TITLE
Function Syntaxe to validate/manipulate inputs

### ISSUE THREAD

**Issue by leoborlot** [openblocks-dev/openblocks#43]
Hi guys, i've trying to creata a CRUD for my business, and I need to check if a input was empyt or the value is a validty format. 
The pictures is only a test to set field "only run when", i look in to documentation and dont found how sintaxe i need to use to create theses functions and validate the fields?

 
![chrome_QIFOusmRwz](https://user-images.githubusercontent.com/20361821/202827986-38187d0f-af4f-475d-8e26-d05135dec34b.png)

**Comment by ggbond2077** [comment]
1. You should wrap all your JavaScript code in '{{ }}',  therefore the condition is write as:

![image](https://user-images.githubusercontent.com/20850558/202832193-b3a37ae8-356d-4112-91b6-0dd2df92872d.png)

2. and you can check the input filed's empty value from left side bar, which is "" instead of null.

![image](https://user-images.githubusercontent.com/20850558/202832242-bf7f3ad9-4de5-42e3-affb-494ef7b1c231.png)


We will have doc about how to use JavaScript in OB soon.

**Comment by leoborlot** [comment]
Very good, thank!
